### PR TITLE
Add support for specifying custom templates path

### PR DESCRIPTION
**Pull request by nflx**

### CODE REVIEW

**Comment by svtfrida** [comment]
Would it be more coherent to rename `template_path` to `custom_template_path`? SInce it is referred to as "custom template" in most other contexts.

**Comment by nflx** [comment]
> Would it be more coherent to rename `template_path` to `custom_template_path`? SInce it is referred to as "custom template" in most other contexts.

I was only trying to push on the fact that the parameters is for a more customized use-case.

If it's possible I'd rather drop some of the "custom " wording to better harmonize with the `template_path` and `ORM_TEMPLATE_PATH` parameters and variables. To lessen any confusion.

**Comment by svtfrida** [comment]
That's even better, good suggestion.

**Comment by splushii** [comment]
What is the use case?

**Comment by nflx** [comment]
@splushii The use case is to be able to change things in the haproxy template that doesn't affect the rest of the code without requiring a new release of the code.

**Comment by nflx** [comment]
I see your point. Unfortunately our attention is needed elsewhere for the moment. We might return to this. Maybe not.

**Pull request closed without merging**
